### ISSUE TITLE
threading.client consumes a lot of CPU while not active

### ISSUE THREAD

**Issue by vstadnytskyi** [vstadnytskyi/caproto-sandbox#5]
I have noticed that my CPU utilization goes up(+25% one core) substantially when I create a very simple threading.client before even connection to any PVs. consumes a lot of CPU while not active.

<img width="920" alt="image" src="https://user-images.githubusercontent.com/29989124/67026240-5f5ad780-f0d5-11e9-8c5e-2f3825447f7c.png">

My test code:
https://github.com/vstadnytskyi/caproto-sandbox/blob/master/caproto_sandbox/threading_client_bug.py
```
#!/usr/bin/env python3
import psutil
from time import sleep
sleep(2)
print(psutil.cpu_percent(percpu = True),'start')

from caproto.threading.client import Context
sleep(2)
print(psutil.cpu_percent(percpu = True), 'import Context')

ctx = Context()
sleep(2)
print(psutil.cpu_percent(percpu = True),'2 seconds after ctx = Context()')
sleep(2)
print(psutil.cpu_percent(percpu = True),'4 seconds after ctx = Context()')
sleep(2)
print(psutil.cpu_percent(percpu = True),'6 seconds after ctx = Context()')

```
Output when I run the code. See how 
```
$ python3 caproto_sandbox/threading_client_test.py
[13.6, 4.0, 13.0, 2.5] start
[25.5, 5.7, 20.9, 4.3] import Context
[37.1, 11.4, 56.2, 10.9] 2 seconds after ctx = Context()
[43.5, 20.0, 51.0, 15.4] 4 seconds after ctx = Context()
[51.5, 25.9, 60.5, 20.4] 6 seconds after ctx = Context()
```

**Comment by vstadnytskyi** [comment]
It might be somewhere in these threads
https://github.com/caproto/caproto/blob/497cbd22da5a3ad45f6955570a3c389b17edbb15/caproto/threading/client.py#L964
``` python
self._process_search_results_thread = threading.Thread(
            target=self._process_search_results_loop,
            daemon=True, name='search')
        self._process_search_results_thread.start()

        self._activate_subscriptions_thread = threading.Thread(
            target=self._activate_subscriptions,
            daemon=True, name='activate_subscriptions')
        self._activate_subscriptions_thread.start()

        self.selector = SelectorThread(parent=self)
        self.selector.start()
```

**Comment by tacaswell** [comment]
I can not reproduce this locally.

The search results thread should be blocking on https://github.com/caproto/caproto/blob/497cbd22da5a3ad45f6955570a3c389b17edbb15/caproto/threading/client.py#L1085-L1092 which should only hot-loop at 2Hz and the activate subscriptions thread should mostly be block on https://github.com/caproto/caproto/blob/497cbd22da5a3ad45f6955570a3c389b17edbb15/caproto/threading/client.py#L1201-L1204 which is going at 10Hz.  Neither of those should be able to saturate a CPU.  Neither should have any work to do as you have not done any searches yet nor have you set up any subscriptions....

My knee-jerk guess is that you are in https://github.com/caproto/caproto/blob/497cbd22da5a3ad45f6955570a3c389b17edbb15/caproto/threading/client.py#L579-L690 and have noisy neighbors putting stuff on UDP broadcast that it should not.

Can you turn the logging up to see what message we are seeing?

**Comment by vstadnytskyi** [comment]
If I add this code. I assume this is what you meant by "turn the logging up". I didn't see any verbose attributes in the Context() class.

```
import logging;
    logging.basicConfig(level=logging.DEBUG, format="%(asctime)s %(levelname)s: %(message)s")
```

I see this:
```
In [4]: 2019-10-17 15:05:31,383 DEBUG: Sending 4 SearchRequests
2019-10-17 15:05:31,397 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:05:40,233 DEBUG: Sending 4 SearchRequests
2019-10-17 15:05:40,236 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:05:45,236 DEBUG: Sending 4 SearchRequests
2019-10-17 15:05:45,236 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:05:50,240 DEBUG: Sending 4 SearchRequests
2019-10-17 15:05:50,240 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:05:55,240 DEBUG: Sending 4 SearchRequests
2019-10-17 15:05:55,241 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:06:00,244 DEBUG: Sending 4 SearchRequests
2019-10-17 15:06:00,245 DEBUG: Sending 176 bytes to 255.255.255.255:5064
2019-10-17 15:06:05,247 DEBUG: Sending 4 SearchRequests
2019-10-17 15:06:05,248 DEBUG: Sending 176 bytes to 255.255.255.255:5064
```

**Comment by vstadnytskyi** [comment]
I have the same behaviour if I go on a guest wifi (presumable no IOCs are running on wifi)

```
$ python3 caproto_sandbox/threading_client_bug.py
[19.5, 7.0, 17.0, 5.0] start
[22.3, 6.8, 20.0, 5.0] import Context
[39.0, 15.3, 55.4, 15.3] 2 seconds after ctx = Context()
[41.3, 16.5, 51.5, 12.0] 4 seconds after ctx = Context()
[42.3, 16.0, 52.2, 16.0] 6 seconds after ctx = Context()
```

and if I completely disconnect wifi.
```
$ python3 caproto_sandbox/threading_client_bug.py
[56.8, 28.4, 45.0, 22.5] start
[44.2, 16.6, 43.8, 16.6] import Context
Broadcaster registration failed on init
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/threading/client.py", line 457, in send
    self.udp_sock.sendto(bytes_to_send, (host, specified_port))
OSError: [Errno 51] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/threading/client.py", line 372, in __init__
    self._register()

  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/threading/client.py", line 396, in _register
    self.send(ca.EPICS_CA2_PORT, command)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/caproto/threading/client.py", line 461, in send
    f'{host}:{specified_port}') from ex
caproto._utils.CaprotoNetworkError: [Errno 51] Network is unreachable while sending 16 bytes to 255.255.255.255:5065
[53.4, 18.8, 61.1, 12.6] 2 seconds after ctx = Context()
[52.2, 16.5, 54.3, 15.0] 4 seconds after ctx = Context()
[50.0, 11.4, 56.2, 11.9] 6 seconds after ctx = Context()
```
